config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root to: "users#show"
  end

  root to: "static_pages#index"

  devise_for :users, controllers: {
    sessions:      "users/sessions",
    passwords:     "users/passwords",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    invitations:   "users/invitations"
  }

  namespace :admin do
    resources :users, except: [:new, :create]
    resources :polls, except: [:new, :create]

    get '/remove_role', to: 'users#remove_role_link'
    get '/remove_user', to: 'users#delete_user_link'
  end

  resources :groups
  get  '/edit_user_emails',   to: 'groups#edit_user_emails'
  post '/change_users_group', to: 'groups#change_users_group'
  get  '/remove_user',        to: 'groups#remove_user_from_group_path'

  resources :polls
  resources :poll_options
  resources :votes

  # participants controller
  get  '/new_poll_roles',       to: 'participants#new_poll_roles'
  post '/create_poll_roles',    to: 'participants#create_poll_roles'

  get  '/add_groups',           to: 'participants#add_groups'
  post '/add_poll_groups',      to: 'participants#add_poll_groups'

  get '/remove_user_from_poll', to: 'participants#remove_user_from_poll'
end

app/models/poll.rb
class Poll < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  resourcify

  has_many :poll_options, dependent: :destroy
  has_many :polls_groups
  has_many :groups, through: :polls_groups

  validates :title, presence: true

  accepts_nested_attributes_for :poll_options, reject_if: lambda {|attributes| attributes['title'].blank?}, allow_destroy: true

  def timed?

  end

  def all_users_voted?
    user_votes         = 0
    total_user_votes   = 0
    roles_count        = 0
    total_poll_options = self.poll_options.count

    self.roles.each do |role|
      roles_count = roles_count + role.users.count
    end

    self.poll_options.each do |poll_option|
      user_votes = user_votes + poll_option.votes.count
    end

    total_avaliable_votes = roles_count * total_poll_options

    if total_avaliable_votes == user_votes
      self.update(active: false)
    end
  end

  def inactive?
    self.active == false
  end
end

app/controllers/admin/polls_controller.rb
class Admin::PollsController < Admin::AdminController

  before_action :set_poll, except: [:index]

  def index
    @polls = Poll.all
    authorize :admin, :index?
  end

  def show
    authorize :admin, :show?
  end

  def edit
    authorize :admin, :edit?
  end

  def update
    authorize :admin, :edit?
  end

  private

  def set_poll
    @poll = Poll.find(params[:id])
  end

end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  helper PollsHelper

  before_action :authenticate_user!

  before_action :set_poll, except: [:index]

  def index
    @polls = Poll.all
  end

  def show
    @vote = Vote.new
  end

  def new
    @poll.poll_options.build
  end

  def create
    @poll.assign_attributes(poll_params)
    if @poll.save
      current_user.add_role :resource_admin, @poll
      flash[:notice] = "Poll has been created!"
      redirect_to poll_path(@poll)
    else
      flash[:alert] = "Poll not created"
      render "new"
    end
  end

  def edit
    @poll.poll_options.build
  end

  def update
    if @poll.update(poll_params)
      flash[:notice] = "You have updated the Poll!"
      redirect_to poll_path(@poll)
    else
      flash[:alert] = "Poll unable to update."
    end
  end

  def destroy
    @poll.destroy
    flash[:notice] = "Poll removed"
    redirect_to root_url
  end

  private

  def set_poll
    @poll = params[:id].present? ? Poll.friendly.find(params[:id]) : Poll.new
  end

  def poll_params
    params.require(:poll).permit(
      :active,
      :description,
      :title,
      poll_options_attributes: [
        :_destroy,
        :description,
        :id,
        :poll_id,
        :title,
        :user_id,
        images: []]
    )
  end
end

app/helpers/polls_helper.rb
module PollsHelper
  
  def user_vote_button(poll)
    if current_user.voted_for_poll?(poll)
      button_tag("You Voted!", class: ["btn", "btn-primary", "js-scroll-trigger"], type: "button")
    else
      button_tag("Vote", class: ["btn", "btn-primary", "js-scroll-trigger"], name: "button", type: "button", id: "masterSave", onclick: "submitAllVotes()" )
    end
  end
end

app/views/admin/polls/edit.html.erb
<div class="poll-edit">
  <%= render partial: "polls/form" %>
  <%= link_to 'Add Users', new_participants_path(id: @poll), remote: true %>
</div>

app/views/admin/polls/index.html.erb
<div class="admin-polls-index" style="text-align: center;">

  <h5>All Polls</h5>
  <input type="text" id="myInput" onkeyup="searchTable()" placeholder="Search for Polls..." title="Type in a name">
  <div class="table-wrapper">
    <table id="myTable" class="fl-table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>View</th>
          <th>Edit</th>
        </tr>
      </thead>
      <tbody>
        <% if @polls.any? %>
          <% @polls.each do |poll| %>
            <tr>
              <td><%= poll.title %></td>
              <td><%= poll.description %></td>
              <td> <%= link_to 'View poll', poll_path(poll.id) %></td>
              <td><%= link_to '', edit_poll_path(poll.id), class: "fa fa-edit" %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<script>
  searchTable();
</script>