config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root to: "users#show"
  end

  root to: "static_pages#index"

  devise_for :users, controllers: {
    sessions:      "users/sessions",
    passwords:     "users/passwords",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    invitations:   "users/invitations"
  }

  namespace :admin do
    resources :users, except: [:new, :create]
    resources :polls, except: [:new, :create]

    get '/remove_role', to: 'users#remove_role_link'
    get '/remove_user', to: 'users#delete_user_link'
  end

  resources :groups
  get  '/edit_user_emails',   to: 'groups#edit_user_emails'
  post '/change_users_group', to: 'groups#change_users_group'
  get  '/remove_user',        to: 'groups#remove_user_from_group_path'

  resources :polls
  resources :poll_options
  resources :votes

  # participants controller
  get  '/new_poll_roles',       to: 'participants#new_poll_roles'
  post '/create_poll_roles',    to: 'participants#create_poll_roles'

  get  '/add_groups',           to: 'participants#add_groups'
  post '/add_poll_groups',      to: 'participants#add_poll_groups'

  get '/remove_user_from_poll', to: 'participants#remove_user_from_poll'
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user

  has_many :users_groups
  has_many :polls_groups

  has_many :users, through: :users_groups
  has_many :polls, through: :polls_groups

  accepts_nested_attributes_for :users

  validates :title, presence: true
end

app/models/groups.rb
class Group < ApplicationRecord
  belongs_to :user

  has_many :users, through: :user_groups
  has_many :polls, through: :poll_groups
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_action :authenticate_user!

  before_action :set_group, except: [:index]

  def index
    @groups = Group.all
  end

  def show
  end

  def new
    @group.build_user
  end

  def create
    @group.assign_attributes(group_params)
    if @group.save
      flash[:notice] = "Group Created!"
      redirect_to edit_group_path(@group)
    else
      flash[:alert] = "Group not created."
      render "new"
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      flash[:notice] = "You have created a group!"
      redirect_to group_path(@group)
    else
      flash[:alert] = "Group unable to be updated."
    end
  end

  def destroy
    @group.destroy
    flash[:success] = "Group removed"
    redirect_to root_url
  end

  def edit_user_emails
    if current_user.email_groups.empty?
      @users = []
    else
      current_user.email_groups.each do |group|
        @users = group.users.map { |user| [user.email, user.email]}
      end
    end

    render 'form.js'
  end

  def change_users_group
    emails        = params[:user_group_emails]
    group         = Group.find(params[:group_id])
    new_users     = []

    emails.each do |email|
      email = email.to_s
      email = email.gsub(/[," ]/, '')
      email = email.gsub("[", "")
      email = email.gsub("]", "")
      user  = User.find_by(email: email)

      if user.nil?
        new_user = User.invite!(email: email)
        new_users = new_users.push(email)

        flash[:notice] = "#{new_users} doesnt exist. An invitation has been sent."
        group.users << new_user
      else
        group.users << user
      end
    end
    redirect_back(fallback_location: root_path)
  end

  def remove_user_from_group_path( options = {  })
    user  = User.find(params[:user_id])
    group = Group.find(params[:group_id])

    group.users.delete(user)
    redirect_to root_url
  end

  private

  def set_group
    @group = params[:id].present? ? Group.find(params[:id]) : current_user.groups.new
  end

  def group_params
    params.require(:group).permit(
      :description,
      :title,
      :user_id,
      users_attributes: [:user_id, :email]
    )
  end
end

app/views/groups/_change_users_group.html.erb
<div class="modal-form">
  <%= form_tag "/change_users_group", remote: true do %>
    <%= hidden_field_tag :group_id, @group.id %>

    <%= label_tag :user_group_emails %><br />
    <%= select_tag :user_group_emails, options_for_select(@users),
          {class: 'select-two-class', multiple: true, include_blank: false, include_hidden: false, style: "width: 100%;"} %>

    <div class="participants-bottom-button">
      <%= submit_tag "Select", class: "btn btn-primary js-scroll-trigger" %>
    </div>
  <% end %>
</div>

<script>
  $(".select-two-class").select2({
    tags: true,
    multiple: true,
    tokenSeparators: [',', ' '],
    class: "form-control"
  });
</script>

app/views/groups/_form.html.erb
<div class="form">
  <%= form_for (@group) do |f| %>
    <div class="container-fluid">
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <% if @group.errors.any? %>
        <%= @group.errors.full_messages %>
      <% end %>

      <div data-step="1" data-intro='Made a mistake? Edit the group name.'>
      <%= f.text_field :title, class: "form-input",
          placeholder: "Title" %><br />
      </div>

      <div data-step="2" data-intro='Or the description.'>
      <%= f.text_area :description, class: "form-input",
          placeholder: "Short Description" %><br />
      </div>

      <%= f.submit "Submit", class: "btn btn-primary js-scroll-trigger" %><br />
    </div>
  <% end %>

    <%= link_to 'Back', :back, class: "back-button form-path-link " %><br />

  <% if action_name == 'edit' %>
    <div data-step="3" data-intro='and add some emails while your at it!'><%= link_to 'Add Emails', edit_user_emails_path(id: @group), class: "app-standard-button", remote: true %></div><br /><br /><br /><br />
    <%= link_to 'Delete', @group, method: :delete, data: { confirm: "Are you sure?" }, class: "form-path-link delete-resource-button" %><br />
  <% end %>
</div>

app/views/groups/_index.html.erb
<div class="group-index">

  <div class="group-index-header">
    <div>
      <%= link_to "Create New Group", new_group_path, class: "btn btn-primary js-scroll-trigger create-resource-call-to-action" %>
    </div>
    <% if current_user.email_groups.any? %>
    <input type="text" id="groupInput" class="search-field" onkeyup="searchTable('group')" placeholder="Search Groups..." title="Type in a title">
  </div>

    <div class="table-wrapper">
      <table id="groupTable" class="fl-table">
        <thead>
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th>View</th>
            <th>Edit</th>
            <th data-toggle="tooltip" data-placement="top" title="Add emails to a group inorder to add multiple people to many different polls (example: Famly members)">Add Emails <a class="fa fa-info-circle"></a></th>
          </tr>
        </thead>
        <tbody>
          <% current_user.email_groups.each do |group| %>
            <tr>
              <td><%= group.title %></td>
              <td><%= group.description %></td>
              <td><%= link_to 'View Group', group_path(group), class: "table-link" %></td>
              <td><%= link_to '', edit_group_path(group), class: "table-link fa fa-edit" %></td>
              <td><%= link_to 'Add Emails', edit_user_emails_path(id: group), class: "table-link", remote: true %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

<script>
  searchTable("group");
</script>

app/views/groups/edit.html.erb
<div class="group-edit">
  <button class="app-standard-button" onclick="runGroupEditTour()">What do I do?</button>
  <%= form_title(@group) %>
  <%= render partial: "groups/form" %>
</div>

<script>
  function runGroupEditTour() {
    introJs().start();
  }
</script>

app/views/groups/form.js.erb
$(".modal-title").html("User Emails");
$(".modal-body").html("<%= escape_javascript(render partial: '/groups/change_users_group', locals: { group: @group }) %>");
$("#myModal").modal("show");

app/views/groups/new.html.erb
<div class="group-new">
  <%= form_title(@group) %>
  <%= render partial: "groups/form" %>
</div>

app/views/groups/show.html.erb
<div class="group-show" style="text-align: center;">
  <h5><%= @group.title %></h5>
  <h6><%= @group.description %></h6>
  <%= link_to 'Edit group', edit_group_path(@group), class: "app-standard-button" %>
  <%= link_to 'Add Emails', edit_user_emails_path(id: @group), class: "app-standard-button", remote: true %>
  <%= link_to 'Back', :back, class: "form-path-link " %>
  <% if @group.users.any? %>
    <input type="text" id="myInput" onkeyup="searchTable()" placeholder="Search for emails..." title="Type in a name">

    <div class="table-wrapper">
      <table id="myTable" class="fl-table">
        <thead>
          <tr>
            <th>Email</th>
            <th>Remove</th>
          </tr>
        </thead>
        <tbody>
          <% @group.users.each do |user| %>
            <tr>
              <td><%= user.email %></td>
              <td><%= link_to 'Remove', remove_user_path(user_id: user.id, group_id: @group.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

<script>
 searchTable();
</script>