config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root to: "users#show"
  end

  root to: "static_pages#index"

  devise_for :users, controllers: {
    sessions:      "users/sessions",
    passwords:     "users/passwords",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    invitations:   "users/invitations"
  }

  namespace :admin do
    resources :users, except: [:new, :create]
    resources :polls, except: [:new, :create]

    get '/remove_role', to: 'users#remove_role_link'
    get '/remove_user', to: 'users#delete_user_link'
  end

  resources :groups
  get  '/edit_user_emails',   to: 'groups#edit_user_emails'
  post '/change_users_group', to: 'groups#change_users_group'
  get  '/remove_user',        to: 'groups#remove_user_from_group_path'

  resources :polls
  resources :poll_options
  resources :votes

  # participants controller
  get  '/new_poll_roles',       to: 'participants#new_poll_roles'
  post '/create_poll_roles',    to: 'participants#create_poll_roles'

  get  '/add_groups',           to: 'participants#add_groups'
  post '/add_poll_groups',      to: 'participants#add_poll_groups'

  get '/remove_user_from_poll', to: 'participants#remove_user_from_poll'
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :email, use: :slugged

  rolify
  devise :confirmable, :database_authenticatable, :invitable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :poll_options
  has_many :votes
  has_many :users_groups

  has_many :groups, through: :users_groups
  has_many :email_groups, class_name: "Group", foreign_key: "user_id"

  def voted_for_option?(poll_option)
    poll_option.votes.find_by(user_id: self.id).nil?
  end

  def voted_for_poll?(poll)
    poll_options = poll.poll_options
    user_votes   = []

    poll_options.ids.each do |option_id|
      vote = Vote.find_by(user_id: self.id, poll_option_id: option_id)

      if vote
        user_votes << vote
      end
    end
    if user_votes.count == poll_options.count
      return true
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController

  before_action :set_user, except: [:index]

  def index
    @users = User.all
    authorize :admin, :index?
  end

  def show
    authorize :admin, :show?
  end

  def edit
    authorize :admin, :edit?
  end

  def update
    authorize :admin, :update?
  end

  def remove_role_link( options = {  })
    user = User.find(params[:user_id])
    poll = Poll.find(params[:resource_id])
    name = params[:name].to_sym
    user.remove_role(name, poll)

    redirect_back(fallback_location: root_path)
  end

  def delete_user_link( options = {  })
    user = User.find(params[:id])
    user.destroy
    flash[:notice] = "User destroyed."
    redirect_to admin_users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  # def update
  #   if some_condition
  #     redirect_to root_path
  #   else
  #     super
  #   end
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    render "edit_user_form.js"
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def new
    render "sign_in_form.js"
  end

  def create
    self.resource = warden.authenticate(auth_options)
  
    if self.resource
      set_flash_message(:notice, :signed_in) if is_flashing_format?
      sign_in(resource_name, resource)
      yield resource if block_given?
      respond_with resource, location: after_sign_in_path_for(resource)
    else
      redirect_to root_path 
      flash[:alert] = "Incorrect email or password."
    end
  end

  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  def new
    super
  end

  # POST /resource/unlock
  def create
    super
  end

  # GET /resource/unlock?unlock_token=abcdef
  def show
    super
  end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    if user_signed_in?
      @user_polls = Poll.with_roles([:resource_admin, :user], current_user)
    else
      redirect_to sign_in_path
    end
  end
end

app/views/admin/users/index.html.erb
<div class="Admin-users-index" style="text-align: center;">

  <h5>All Users</h5>
  <input type="text" id="myInput" onkeyup="searchTable()" placeholder="Search for emails..." title="Type in a name">
  <div class="table-wrapper">
    <table id="myTable" class="fl-table">
      <thead>
        <tr>
          <th>Email</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>View</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.email %></td>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= link_to('View', admin_user_path(user.id)) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<script>
  searchTable();
</script>

app/views/admin/users/show.html.erb
<div class="admin-user-show" style="text-align: center;">
  <h5><%= @user.email %></h5>
  <div class="table-wrapper">
    <table class="fl-table">
      <thead>
        <tr>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Email</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @user.first_name %></td>
          <td><%= @user.last_name %></td>
          <td><%= @user.email %></td>
          <th><%= link_to 'Delete User', admin_remove_user_path(id: @user.id), data: { confirm: "Are you sure?" } %></th>
        </tr>
      </tbody>
    </table>
  </div>

  <% if @user.roles.any? %>
    <h5><%= @user.email %> Roles</h5>
    <div class="table-wrapper">
      <table class="fl-table">
        <thead>
          <tr>
            <th>Resource Id</th>
            <th>Role Name</th>
            <th>Role Id</th>
            <th>Delete Role</th>
          </tr>
        </thead>
        <tbody>
          <% @user.roles.each do |role| %>
            <tr>
              <td><%= role.resource_id %></td>
              <td><%= role.name %></td>
              <td><%= role.id %></td>
              <td><%= link_to 'Delete Role', admin_remove_role_path(resource_id: role.resource_id, name: role.name, user_id: @user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <h5><%= @user.email %> has no roles.</h5>
  <% end %>
</div>